Repository StanfordBDHG/ENGAGE-HF-Firebase, pull requests merged in 2024-10, with the labels that each got.

#142 Seed clinician messages
  functions/data/debug/users.json
  functions/src/functions/defaultSeed.ts
  functions/src/services/seeding/debugData/debugDataService.ts
Labels: enhancement

#148 Add writing permission for production deployment
  .github/workflows/production.yml
Labels: bug

#139 Handle multiple medications per class
  functions/src/models/medicationRequestContext.ts
  functions/src/services/database/databaseService.ts
  functions/src/services/database/firestoreService.ts
  functions/src/services/medication/databaseMedicationService.ts
  functions/src/services/medication/medicationService.ts
  functions/src/services/message/defaultMessageService.ts
  functions/src/services/patient/patientService.mock.ts
  functions/src/services/recommendation/recommendationService.test.ts
  functions/src/services/recommendation/recommenders/betaBlockerRecommender.test.ts
  functions/src/services/recommendation/recommenders/diureticRecommender.test.ts
  functions/src/services/recommendation/recommenders/mraRecommender.test.ts
  functions/src/services/recommendation/recommenders/rasiRecommender.test.ts
  functions/src/services/recommendation/recommenders/recommender.ts
  functions/src/services/recommendation/recommenders/sglt2iRecommender.test.ts
  functions/src/services/trigger/triggerService.ts
  functions/src/services/user/userService.mock.ts
  functions/src/tests/mocks/firestore.ts
Labels: enhancement

#146 Allow unenrolled users to read their collections even before enrolling
  firestore.rules
  functions/src/tests/rules/userCollections.test.ts
Labels: bug

#140 Service Account Setup
  functions/models/package-lock.json
  functions/package-lock.json
  functions/package.json
  functions/src/functions/helpers.ts
  functions/src/healthSummary/generate.test.ts
Labels: enhancement

#154 Update recommendation descriptions
  functions/src/services/recommendation/recommendationService.ts
Labels: enhancement

#160 Update Organization Contact Information
  functions/data/organizations.json
Labels: enhancement

#162 Service Account Setup for onSchedule & blocking functions
  functions/src/functions/blocking.ts
  functions/src/functions/helpers.ts
  functions/src/functions/onSchedule.ts
Labels: bug

#163 Update dependencies
  functions/models/package-lock.json
  functions/package-lock.json
Labels: dependencies

#166 Auto-Initializing Deployment Setup
  functions/src/functions/blocking.ts
  functions/src/services/history/databaseHistoryService.ts
  functions/src/services/history/historyService.ts
  functions/src/services/trigger/triggerService.ts
Labels: enhancement

#165 Owner Messages
  functions/models/src/types/userMessage.ts
  functions/src/services/message/defaultMessageService.ts
  functions/src/services/message/messageService.ts
  functions/src/services/seeding/debugData/debugDataService.ts
  functions/src/services/trigger/triggerService.test.ts
  functions/src/services/trigger/triggerService.ts
  functions/src/services/user/databaseUserService.ts
  functions/src/services/user/userService.mock.ts
  functions/src/services/user/userService.ts
Labels: enhancement

#167 Indexes Config
  firebase.json
  firestore.indexes.json
  firestore.indexes.json.license
Labels: enhancement

#168 Update non-patient enrollment logic
  functions/src/functions/blocking.ts
  functions/src/functions/enrollUser.ts
  functions/src/services/trigger/triggerService.ts
  functions/src/services/user/databaseUserService.ts
  functions/src/services/user/userService.mock.ts
  functions/src/services/user/userService.ts
Labels: enhancement

#169 Extract invitation move/delete logic to after the user enrollment is already finished
  functions/src/functions/enrollUser.test.ts
  functions/src/functions/onUserWritten.ts
  functions/src/services/database/databaseService.ts
  functions/src/services/database/firestoreService.ts
  functions/src/services/user/databaseUserService.ts
  functions/src/services/user/userService.mock.ts
  functions/src/services/user/userService.ts
Labels: enhancement

#175 Allow nonexisting users to be queried & improve error logging
  firestore.rules
  functions/src/functions/helpers.ts
  functions/src/tests/rules/users.test.ts
Labels: bug
