Repository StanfordBDHG/ENGAGE-HF-Firebase, pull requests merged in 2024-09, with the labels that each got.

#112 Reduce Firestore Accesses to only relevant data
  functions/models/src/fhir/fhirObservation.ts
  functions/src/extensions/array.ts
  functions/src/models/healthSummaryData.ts
  functions/src/models/vitals.ts
  functions/src/services/contraindication/defaultContraindicationService.test.ts
  functions/src/services/healthSummary/databaseHealthSummaryService.ts
  functions/src/services/healthSummary/healthSummaryService.mock.ts
  functions/src/services/healthSummary/healthSummaryService.ts
  functions/src/services/patient/databasePatientService.ts
  functions/src/services/patient/patientService.mock.ts
  functions/src/services/patient/patientService.ts
  functions/src/services/recommendation/recommendationService.test.ts
  functions/src/services/recommendation/recommendationService.ts
  functions/src/services/recommendation/recommenders/betaBlockerRecommender.test.ts
  functions/src/services/recommendation/recommenders/betaBlockerRecommender.ts
  functions/src/services/recommendation/recommenders/diureticRecommender.test.ts
  functions/src/services/recommendation/recommenders/mraRecommender.test.ts
  functions/src/services/recommendation/recommenders/rasiRecommender.test.ts
  functions/src/services/recommendation/recommenders/rasiRecommender.ts
  functions/src/services/recommendation/recommenders/sglt2iRecommender.test.ts
  functions/src/services/seeding/staticData/rxNormService.ts
  functions/src/services/symptomScore/defaultSymptomScoreCalculator.test.ts
  functions/src/services/trigger/triggerService.ts
  functions/src/tests/mocks/recommendationVitals.ts
Labels: enhancement

#113 Add RxNorm testing
  functions/data/medications.json
  functions/package.json
  functions/src/functions/defaultSeed.test.ts
  functions/src/services/factory/defaultServiceFactory.ts
  functions/src/services/seeding/staticData/rxNorm/rxNormApi.test.ts
  functions/src/services/seeding/staticData/rxNorm/rxNormApi.ts
  functions/src/services/seeding/staticData/rxNorm/rxNormModels.ts
  functions/src/services/seeding/staticData/rxNorm/rxNormService.test.ts
  functions/src/services/seeding/staticData/rxNorm/rxNormService.ts
  functions/src/services/seeding/staticData/staticDataService.test.ts
  functions/src/services/seeding/staticData/staticDataService.ts
  functions/src/tests/functions/testEnvironment.ts
  functions/src/tests/testFlags.ts
  package.json
Labels: enhancement

#122 Release Models Package using NPM
  .github/workflows/release-models-package.yml
  functions/models/README.md
  functions/models/package.json
Labels: enhancement

#123 Usage Documentation
  README.md
  functions/package.json
  package.json
Labels: documentation

#120 Increase logging to more easily identify issues later on
  functions/src/extensions/array.ts
  functions/src/functions/blocking.ts
  functions/src/functions/checkInvitationCode.ts
  functions/src/functions/createInvitation.ts
  functions/src/functions/customSeed.ts
  functions/src/functions/defaultSeed.ts
  functions/src/functions/deleteInvitation.ts
  functions/src/functions/deleteUser.ts
  functions/src/functions/dismissMessage.ts
  functions/src/functions/exportHealthSummary.ts
  functions/src/functions/getUsersInformation.ts
  functions/src/functions/helpers.ts
  functions/src/functions/onSchedule.ts
  functions/src/functions/registerDevice.test.ts
  functions/src/functions/registerDevice.ts
  functions/src/functions/unregisterDevice.ts
  functions/src/functions/updateStaticData.ts
  functions/src/functions/updateUserInformation.ts
  functions/src/healthSummary/generate.ts
  functions/src/services/contraindication/defaultContraindicationService.test.ts
  functions/src/services/contraindication/defaultContraindicationService.ts
  functions/src/services/credential/credential.ts
  functions/src/services/database/databaseConverter.ts
  functions/src/services/message/defaultMessageService.ts
  functions/src/services/recommendation/recommendationService.test.ts
  functions/src/services/seeding/debugData/debugDataService.ts
  functions/src/services/seeding/seedingService.ts
  functions/src/services/seeding/staticData/rxNorm/rxNormApi.ts
  functions/src/services/seeding/staticData/rxNorm/rxNormService.ts
  functions/src/services/trigger/triggerService.ts
  functions/src/services/user/databaseUserService.test.ts
  functions/src/services/user/databaseUserService.ts
Labels: enhancement

#125 Build Models package before publishing
  .github/workflows/release-models-package.yml
  functions/models/package.json
Labels: enhancement

#127 Add providerName extension URL to FHIRExtensionUrl enum
  functions/models/src/codes/codes.ts
Labels: enhancement

#130 Setup Deployment
  .github/workflows/beta-deployment.yml
  .github/workflows/build-and-test.yml.yml
  .github/workflows/codeql.yml
  .github/workflows/deployment.yml
  .github/workflows/lintbuildandtest.yml
  .github/workflows/monthly-markdown-link-check.yml
  .github/workflows/production.yml
  .github/workflows/reuse.yml
  README.md
Labels: enhancement

#135 Fix Deployment Actions
  .github/workflows/build-and-test.yml
  README.md
Labels: enhancement

#136 Fix README
  README.md
Labels: documentation

#129 Update dependencies
  functions/models/package-lock.json
  functions/package-lock.json
Labels: dependencies

#124 Indexes doc
  README.md
Labels: documentation

#126 Clinician messages
  README.md
  functions/data/debug/users.json
  functions/models/src/types/user.ts
  functions/models/src/types/userMessage.ts
  functions/models/src/types/userRegistration.ts
  functions/src/functions/checkInvitationCode.test.ts
  functions/src/functions/createInvitation.test.ts
  functions/src/functions/defaultSeed.ts
  functions/src/functions/deleteInvitation.test.ts
  functions/src/services/message/defaultMessageService.ts
  functions/src/services/seeding/debugData/debugDataService.ts
  functions/src/services/trigger/triggerService.test.ts
  functions/src/services/trigger/triggerService.ts
  functions/src/services/user/databaseUserService.ts
  functions/src/services/user/userService.mock.ts
  functions/src/services/user/userService.ts
  functions/src/tests/functions/testEnvironment.ts
  functions/src/tests/resources/seeding/users_0_messages.json
Labels: enhancement

#137 Android Notification Updates
  functions/src/services/message/defaultMessageService.ts
Labels: enhancement

#109 Update invitation logic
  firebasestorage.rules
  firestore.rules
  functions/data/debug/users.json
  functions/models/package-lock.json
  functions/models/src/functions/enrollUser.ts
  functions/models/src/index.ts
  functions/models/src/types/invitation.ts
  functions/package-lock.json
  functions/src/functions/blocking.ts
  functions/src/functions/checkInvitationCode.ts
  functions/src/functions/enrollUser.test.ts
  functions/src/functions/enrollUser.ts
  functions/src/index.ts
  functions/src/services/trigger/triggerService.ts
  functions/src/services/user/databaseUserService.test.ts
  functions/src/services/user/databaseUserService.ts
  functions/src/services/user/userService.mock.ts
  functions/src/services/user/userService.ts
  functions/src/tests/functions/testEnvironment.ts
  functions/src/tests/mocks/firestore.ts
  functions/src/tests/rules/users.test.ts
Labels: enhancement

#138 Update Clinician Messages
  README.md
  functions/models/src/fhir/fhirAppointment.ts
  functions/models/src/helpers/array.ts
  functions/models/src/index.ts
  functions/models/src/types/userMessage.ts
  functions/src/healthSummary/generate+localizations.ts
  functions/src/healthSummary/generate.test.ts
  functions/src/healthSummary/generate.ts
  functions/src/healthSummary/generateChart.test.ts
  functions/src/healthSummary/generateSpeedometer.test.ts
  functions/src/models/healthSummaryData.ts
  functions/src/services/healthSummary/databaseHealthSummaryService.test.ts
  functions/src/services/healthSummary/databaseHealthSummaryService.ts
  functions/src/services/healthSummary/healthSummaryService.mock.ts
  functions/src/services/message/defaultMessageService.ts
  functions/src/services/patient/databasePatientService.ts
  functions/src/services/patient/patientService.mock.ts
  functions/src/services/recommendation/recommenders/betaBlockerRecommender.test.ts
  functions/src/services/recommendation/recommenders/diureticRecommender.test.ts
  functions/src/services/recommendation/recommenders/rasiRecommender.test.ts
  functions/src/services/recommendation/recommenders/recommender.ts
  functions/src/services/recommendation/recommenders/sglt2iRecommender.test.ts
  functions/src/services/seeding/debugData/debugDataService.ts
  functions/src/services/symptomScore/defaultSymptomScoreCalculator.ts
  functions/src/services/trigger/triggerService.ts
  functions/src/tests/mocks/healthSummaryData.ts
  functions/src/tests/resources/emptyHealthSummary.pdf
  functions/src/tests/resources/mockHealthSummary.pdf
  functions/src/tests/resources/seeding/users_0_messages.json
Labels: enhancement

#141 Update functions docs
  README.md
Labels: documentation

#144 Make sure to correctly allow access to user collections
  firestore.rules
  functions/src/tests/rules/userCollections.test.ts
Labels: bug

#145 Feature Docker Container
  Dockerfile
  Dockerfile.license
  README.md
  docker-compose.yml
  docker-compose.yml.license
  functions/package.json
Labels: enhancement
