Repository StanfordBDHG/ENGAGE-HF-Firebase, pull requests merged in 2024-08, with the labels that each got.

#44 Medication Recommendation Data Structure
  README.md
Labels: enhancement

#51 Seeding: Windows
  functions/package.json
Labels: enhancement

#49 Update dependencies
  functions/package-lock.json
  package-lock.json
Labels: dependencies

#55 Add FHIR resourceType property
  functions/data/drugs.json
  functions/data/medications.json
  functions/src/models/fhir/appointment.ts
  functions/src/models/fhir/baseTypes.ts
  functions/src/models/fhir/medication.ts
  functions/src/models/fhir/observation.ts
  functions/src/models/fhir/questionnaire.ts
  functions/src/models/fhir/questionnaireResponse.ts
  functions/src/services/patient/patientService.mock.ts
  functions/src/services/recommendation/recommenders/diureticRecommender.test.ts
  functions/src/services/seeding/debugData/userDebugDataFactory.ts
  functions/src/services/seeding/staticData/rxNormService.ts
  functions/src/tests/mocks/questionnaire.ts
  functions/src/tests/resources/seeding/users_0_appointments.json
  functions/src/tests/resources/seeding/users_0_bloodPressureObservations.json
  functions/src/tests/resources/seeding/users_0_bodyWeightObservations.json
  functions/src/tests/resources/seeding/users_0_creatinineObservations.json
  functions/src/tests/resources/seeding/users_0_dryWeightObservations.json
  functions/src/tests/resources/seeding/users_0_eGfrObservations.json
  functions/src/tests/resources/seeding/users_0_heartRateObservations.json
  functions/src/tests/resources/seeding/users_0_medicationRequests.json
  functions/src/tests/resources/seeding/users_0_potassiumObservations.json
Labels: enhancement

#57 Set Date values as string instead of FIRTimestamp
  functions/data/debug/users.json
  functions/package.json
  functions/src/models/device.ts
  functions/src/models/fhir/appointment.ts
  functions/src/models/fhir/baseTypes.ts
  functions/src/models/fhir/observation.ts
  functions/src/models/fhir/questionnaireResponse.ts
  functions/src/models/message.ts
  functions/src/models/symptomQuestionnaireResponse.ts
  functions/src/models/user.ts
  functions/src/services/fhir/fhirService.ts
  functions/src/services/healthSummary/databaseHealthSummaryService.ts
  functions/src/services/patient/patientService.mock.ts
  functions/src/services/seeding/debugData/debugDataService.ts
  functions/src/services/seeding/debugData/userDebugDataFactory.test.ts
  functions/src/services/seeding/debugData/userDebugDataFactory.ts
  functions/src/services/symptomScore/defaultSymptomScoreCalculator.test.ts
  functions/src/services/symptomScore/defaultSymptomScoreCalculator.ts
  functions/src/services/user/databaseUserService.test.ts
  functions/src/services/user/userService.mock.ts
  functions/src/tests/mocks/questionnaireResponse.ts
  functions/src/tests/resources/seeding/users_0_bloodPressureObservations.json
  functions/src/tests/resources/seeding/users_0_bodyWeightObservations.json
  functions/src/tests/resources/seeding/users_0_heartRateObservations.json
  functions/src/tests/rules/users.test.ts
Labels: bug

#50 Remove wrong example of `patient` value from README
  README.md
Labels: bug

#63 Update Medication Recommendations Section in Readme
  README.md
Labels: enhancement

#64 Move invitation code in the invitation rather than using it as document id
  README.md
  functions/src/functions/auth.ts
  functions/src/functions/invitation.ts
  functions/src/models/invitation.ts
  functions/src/services/user/databaseUserService.test.ts
  functions/src/services/user/databaseUserService.ts
  functions/src/services/user/userService.mock.ts
  functions/src/services/user/userService.ts
  functions/src/tests/mocks/firestore.ts
Labels: enhancement

#65 Skip enrollment check
  functions/src/functions/auth.ts
  functions/src/functions/invitation.ts
  functions/src/services/user/databaseUserService.test.ts
  functions/src/services/user/databaseUserService.ts
  functions/src/services/user/userService.mock.ts
  functions/src/services/user/userService.ts
Labels: bug

#69 Fix Firestore rules
  firestore.rules
Labels: bug

#79 Remaining UserMessage triggers
  functions/src/functions/recommendation.ts
  functions/src/functions/seeding.ts
  functions/src/functions/symptomScore.ts
  functions/src/index.ts
  functions/src/models/fhir/baseTypes/fhirQuestionnaireItem.ts
  functions/src/models/helpers/dateConverter.ts
  functions/src/models/helpers/schemaConverter.ts
  functions/src/models/types/userMedicationRecommendation.ts
  functions/src/models/types/userMessage.ts
  functions/src/services/factory/defaultServiceFactory.ts
  functions/src/services/message/defaultMessageService.ts
  functions/src/services/message/messageService.ts
  functions/src/services/patient/databasePatientService.ts
  functions/src/services/patient/patientService.mock.ts
  functions/src/services/patient/patientService.ts
  functions/src/services/seeding/debugData/debugDataService.ts
  functions/src/services/seeding/seedingService.ts
  functions/src/services/seeding/staticData/rxNormService.ts
  functions/src/services/seeding/staticData/staticDataService.ts
  functions/src/services/seeding/userData/userDataFactory.ts
  functions/src/services/symptomScore/defaultSymptomScoreCalculator.test.ts
  functions/src/services/trigger/triggerService.ts
  functions/src/tests/resources/seeding/users_0_appointments.json
  functions/src/tests/resources/seeding/users_0_bloodPressureObservations.json
  functions/src/tests/resources/seeding/users_0_bodyWeightObservations.json
  functions/src/tests/resources/seeding/users_0_creatinineObservations.json
  functions/src/tests/resources/seeding/users_0_dryWeightObservations.json
  functions/src/tests/resources/seeding/users_0_eGfrObservations.json
  functions/src/tests/resources/seeding/users_0_heartRateObservations.json
  functions/src/tests/resources/seeding/users_0_medicationRequests.json
  functions/src/tests/resources/seeding/users_0_messages.json
  functions/src/tests/resources/seeding/users_0_potassiumObservations.json
Labels: enhancement

#84 Recommendation Algorithm Testing & Contraindication Logic
  functions/data/medicationCodes.json
  functions/data/medications.json
  functions/src/models/fhir/baseTypes/fhirElement.ts
  functions/src/models/fhir/fhirAllergyIntolerance.ts
  functions/src/models/fhir/fhirAppointment.ts
  functions/src/models/fhir/fhirObservation.ts
  functions/src/models/fhir/fhirQuestionnaireResponse.ts
  functions/src/services/contraindication/contraindicationService.ts
  functions/src/services/contraindication/defaultContraindicationService.test.ts
  functions/src/services/contraindication/defaultContraindicationService.ts
  functions/src/services/patient/patientService.mock.ts
  functions/src/services/recommendation/recommendationService.test.ts
  functions/src/services/recommendation/recommendationService.ts
  functions/src/services/recommendation/recommenders/betaBlockerRecommender.test.ts
  functions/src/services/recommendation/recommenders/betaBlockerRecommender.ts
  functions/src/services/recommendation/recommenders/diureticRecommender.test.ts
  functions/src/services/recommendation/recommenders/diureticRecommender.ts
  functions/src/services/recommendation/recommenders/mraRecommender.test.ts
  functions/src/services/recommendation/recommenders/mraRecommender.ts
  functions/src/services/recommendation/recommenders/rasiRecommender.test.ts
  functions/src/services/recommendation/recommenders/rasiRecommender.ts
  functions/src/services/recommendation/recommenders/recommender.ts
  functions/src/services/recommendation/recommenders/sglt2iRecommender.test.ts
  functions/src/services/recommendation/recommenders/sglt2iRecommender.ts
  functions/src/services/references.ts
  functions/src/services/seeding/debugData/debugDataService.ts
  functions/src/services/seeding/staticData/rxNormService.ts
  functions/src/services/trigger/triggerService.ts
  functions/src/tests/mocks/contraindicationService.ts
  functions/src/tests/mocks/questionnaire.ts
  functions/src/tests/resources/contraindications.csv
  functions/src/tests/resources/contraindications.csv.license
  functions/src/tests/resources/medtitrationtest.csv
  functions/src/tests/resources/medtitrationtest.csv.license
  resources/algorithms/BetaBlockers-0.png
  resources/algorithms/BetaBlockers-0.png.license
  resources/algorithms/BetaBlockers-1.png
  resources/algorithms/BetaBlockers-1.png.license
  resources/algorithms/BetaBlockers.png
  resources/algorithms/MRA.png
  resources/algorithms/RASI-0.png
  resources/algorithms/RASI-1.png
  resources/algorithms/SGLT2i.png
Labels: enhancement

#87 Localize Health Summary PDF
  functions/src/functions/healthSummary.ts
  functions/src/healthSummary/generate+localizations.ts
  functions/src/healthSummary/generate.test.ts
  functions/src/healthSummary/generate.ts
  functions/src/healthSummary/generateSpeedometer+localizations.ts
  functions/src/healthSummary/generateSpeedometer.test.ts
  functions/src/healthSummary/generateSpeedometer.ts
  functions/src/models/healthSummaryData.ts
  functions/src/services/healthSummary/databaseHealthSummaryService.test.ts
  functions/src/services/healthSummary/databaseHealthSummaryService.ts
  functions/src/services/healthSummary/healthSummaryService.ts
  functions/src/services/trigger/triggerService.ts
  functions/src/tests/resources/emptyHealthSummary.pdf
  functions/src/tests/resources/mockHealthSummary.pdf
Labels: enhancement

#92 Algorithm Documentation
  README.md
  resources/algorithms/BetaBlockers-1.png
  resources/algorithms/BetaBlockers-1.png.license
  resources/algorithms/BetaBlockers.png
  resources/algorithms/BetaBlockers.png.license
  resources/algorithms/MRA.png
  resources/algorithms/SGLT2i.png
Labels: documentation

#86 Medication Brand names
  functions/data/medicationCodes.json
  functions/data/medications.json
  functions/src/models/fhir/baseTypes/fhirElement.ts
  functions/src/models/fhir/fhirMedication.ts
  functions/src/services/codes.ts
  functions/src/services/recommendation/recommendationService.ts
  functions/src/services/seeding/staticData/rxNormService.ts
Labels: enhancement

#82 Symptom Score Calculator Testing
  functions/src/services/symptomScore/defaultSymptomScoreCalculator.test.ts
  functions/src/services/symptomScore/defaultSymptomScoreCalculator.ts
  functions/src/tests/resources/symptomScores.csv
  functions/src/tests/resources/symptomScores.csv.license
Labels: enhancement

#88 Functions Documentation
  README.md
  functions/src/functions/message.ts
  functions/src/functions/seeding.ts
  functions/src/functions/user.ts
Labels: documentation

#97 Make sure to install dependencies for Models package before deploying
  .github/workflows/beta-deployment.yml
  .github/workflows/lintbuildandtest.yml
  firebase.json
  functions/package-lock.json
  functions/package.json
  models/package-lock.json
  package-lock.json
  package.json
Labels: bug

#90 Notification Settings
  README.md
  functions/src/services/message/defaultMessageService.ts
  functions/src/services/message/messageService.ts
  functions/src/services/patient/databasePatientService.ts
  functions/src/services/trigger/triggerService.ts
  functions/src/services/user/userService.mock.ts
  models/src/types/user.ts
  models/src/types/userRegistration.ts
Labels: enhancement

#98 (Re-)Add UpdateUserInformation & DeleteUser functions
  functions/src/functions/deleteUser.ts
  functions/src/functions/updateUserInformation.ts
  functions/src/index.ts
  models/src/functions/deleteUser.ts
  models/src/functions/updateUserInformation.ts
  models/src/index.ts
Labels: bug

#99 Reduce Health Summary PDF File Size
  .github/workflows/lintbuildandtest.yml
  functions/src/healthSummary/generate+localizations.ts
  functions/src/healthSummary/generate.test.ts
  functions/src/healthSummary/generate.ts
  functions/src/healthSummary/generateSpeedometer.ts
  functions/src/services/healthSummary/healthSummaryService.mock.ts
  functions/src/services/patient/patientService.mock.ts
  functions/src/tests/resources/emptyHealthSummary.pdf
  functions/src/tests/resources/mockHealthSummary.pdf
  functions/src/tests/resources/mockSpeedometer.svg
Labels: enhancement

#103 Add Functions Testing
  functions/.nycrc.json
  functions/models/src/functions/deleteInvitation.ts
  functions/models/src/index.ts
  functions/package.json
  functions/src/functions/checkInvitationCode.test.ts
  functions/src/functions/checkInvitationCode.ts
  functions/src/functions/createInvitation.test.ts
  functions/src/functions/defaultSeed.test.ts
  functions/src/functions/defaultSeed.ts
  functions/src/functions/deleteInvitation.test.ts
  functions/src/functions/deleteInvitation.ts
  functions/src/functions/deleteUser.test.ts
  functions/src/functions/dismissMessage.test.ts
  functions/src/functions/dismissMessage.ts
  functions/src/functions/getUsersInformation.test.ts
  functions/src/functions/registerDevice.test.ts
  functions/src/functions/registerDevice.ts
  functions/src/functions/updateStaticData.test.ts
  functions/src/functions/updateUserInformation.test.ts
  functions/src/services/database/collections.ts
  functions/src/services/message/defaultMessageService.ts
  functions/src/services/trigger/triggerService.test.ts
  functions/src/services/trigger/triggerService.ts
  functions/src/services/user/databaseUserService.ts
  functions/src/services/user/userService.mock.ts
  functions/src/services/user/userService.ts
  functions/src/tests/functions/testEnvironment.ts
  functions/src/tests/helpers.ts
  package.json
Labels: enhancement

#105 New Testing Data for Algorithms & Symptom Score Calculation
  functions/models/src/codes/references.ts
  functions/src/services/medication/databaseMedicationService.ts
  functions/src/services/recommendation/recommendationService.test.ts
  functions/src/services/symptomScore/defaultSymptomScoreCalculator.test.ts
  functions/src/services/symptomScore/defaultSymptomScoreCalculator.ts
  functions/src/tests/helpers/csv.ts
  functions/src/tests/resources/medtitrationtest.csv
  functions/src/tests/resources/symptomScores.csv
Labels: enhancement

#85 Keep history of changes to the database
  functions/src/functions/onHistoryWritten.ts
  functions/src/index.ts
  functions/src/services/database/collections.ts
  functions/src/services/factory/defaultServiceFactory.ts
  functions/src/services/factory/serviceFactory.ts
  functions/src/services/history/databaseHistoryService.test.ts
  functions/src/services/history/databaseHistoryService.ts
  functions/src/services/history/historyService.ts
  functions/src/tests/functions/testEnvironment.ts
Labels: enhancement

#107 Make sure to not call history changes recursively
  functions/src/functions/onHistoryWritten.ts
Labels: bug

#108 Export unregisterDevice
  functions/src/index.ts
Labels: bug

#110 Reduce query complexity
  functions/src/services/message/defaultMessageService.ts
  functions/src/services/message/messageService.ts
Labels: enhancement
