Repository StanfordBDHG/ENGAGE-HF-Firebase, pull requests merged in 2025-03, with the labels that each got.

#225 Update key point messages in case of inadequate kccq data
  functions/package.json
  functions/src/healthSummary/generate+localizations.ts
  functions/src/healthSummary/keyPointsMessage.test.ts
  functions/src/healthSummary/keyPointsMessage.ts
  functions/src/models/healthSummaryData.ts
  functions/src/services/seeding/staticData/rxNorm/rxNormApi.test.ts
  functions/src/tests/resources/keyPointMessages.csv
  functions/src/tests/testFlags.ts
Labels: enhancement

#227 Update dependencies
  functions/models/package-lock.json
  functions/package-lock.json
Labels: dependencies

#228 Update dependencies (once again)
  functions/package-lock.json
  functions/package.json
  functions/src/healthSummary/pdfGenerator.ts
Labels: dependencies

#235 Health Summary Ranges
  functions/src/healthSummary/generate.ts
  functions/src/models/healthSummaryData.ts
  functions/src/tests/resources/mockHealthSummary.pdf
Labels: enhancement

#239 Health Summary Fixes
  functions/src/healthSummary/generate.ts
  functions/src/models/healthSummaryData.ts
Labels: bug

#242 Implement dismissMessages Function
  functions/models/src/functions/dismissMessages.ts
  functions/models/src/index.ts
  functions/src/functions/dismissMessages.test.ts
  functions/src/functions/dismissMessages.ts
  functions/src/index.ts
  functions/src/services/message/defaultMessageService.ts
  functions/src/services/message/messageService.ts
Labels: enhancement

#244 Fix median body weight check
  functions/src/healthSummary/generate+localizations.ts
  functions/src/healthSummary/generate.ts
  functions/src/models/healthSummaryData.ts
  functions/src/tests/resources/mockHealthSummary.pdf
Labels: bug

#246 Separate KeyPoint messages for lab, patient and both observations missing
  functions/src/healthSummary/keyPointsMessage.test.ts
  functions/src/healthSummary/keyPointsMessage.ts
  functions/src/models/healthSummaryData.ts
  functions/src/tests/resources/keyPointMessages.csv
Labels: enhancement

#247 Update dependencies
  functions/.eslintrc.cjs
  functions/eslint.config.mjs
  functions/models/.eslintrc.cjs
  functions/models/eslint.config.mjs
  functions/models/package-lock.json
  functions/models/package.json
  functions/models/src/fhir/baseTypes/fhirElement.ts
  functions/models/src/functions/getUsersInformation.ts
  functions/models/src/helpers/schemaConverter.ts
  functions/package-lock.json
  functions/package.json
  functions/src/functions/blocking.ts
  functions/src/functions/helpers.ts
  functions/src/services/database/databaseConverter.ts
  functions/src/services/database/databaseService.ts
  functions/src/services/healthSummary/healthSummaryService.mock.ts
  functions/src/services/message/defaultMessageService.ts
  functions/src/services/message/messageService.ts
  functions/src/services/recommendation/recommenders/betaBlockerRecommender.test.ts
  functions/src/services/recommendation/recommenders/rasiRecommender.test.ts
  functions/src/services/seeding/debugData/debugDataService.ts
  functions/src/services/seeding/seedingService.ts
  functions/src/services/seeding/staticData/rxNorm/rxNormService.ts
  functions/src/services/user/databaseUserService.ts
  functions/src/tests/mocks/auth.ts
  functions/src/tests/mocks/firestore.ts
Labels: dependencies

#237 Health Summary Sharing via One-Time-Code
  README.md
  functions/models/src/functions/exportHealthSummary.ts
  functions/models/src/functions/shareHealthSummary.ts
  functions/models/src/index.ts
  functions/models/src/types/userShareCode.ts
  functions/src/env.ts
  functions/src/functions/exportHealthSummary.test.ts
  functions/src/functions/exportHealthSummary.ts
  functions/src/functions/shareHealthSummary.test.ts
  functions/src/functions/shareHealthSummary.ts
  functions/src/index.ts
  functions/src/services/database/collections.ts
  functions/src/services/patient/databasePatientService.ts
  functions/src/services/patient/patientService.mock.ts
  functions/src/services/patient/patientService.ts
  functions/src/tests/functions/testEnvironment.ts
Labels: enhancement
