Repository StanfordBDHG/ENGAGE-HF-Firebase, pull requests merged in 2025-01, with the labels that each got.

#199 Health Summary Updates
  functions/models/src/codes/quantityUnit.ts
  functions/resources/fonts/OpenSans-BoldItalic.ttf
  functions/resources/fonts/OpenSans-BoldItalic.ttf.license
  functions/resources/fonts/OpenSans-Italic.ttf
  functions/resources/fonts/OpenSans-Italic.ttf.license
  functions/src/functions/exportHealthSummary.ts
  functions/src/healthSummary/generate+localizations.ts
  functions/src/healthSummary/generate.ts
  functions/src/healthSummary/keyPointsMessage.test.ts
  functions/src/healthSummary/keyPointsMessage.ts
  functions/src/healthSummary/pdfGenerator.ts
  functions/src/models/healthSummaryData.ts
  functions/src/services/healthSummary/databaseHealthSummaryService.test.ts
  functions/src/services/healthSummary/databaseHealthSummaryService.ts
  functions/src/services/healthSummary/healthSummaryService.mock.ts
  functions/src/services/healthSummary/healthSummaryService.ts
  functions/src/services/patient/patientService.mock.ts
  functions/src/services/trigger/triggerService.ts
  functions/src/tests/helpers/csv.ts
  functions/src/tests/mocks/healthSummaryData.ts
  functions/src/tests/resources/emptyHealthSummary.pdf
  functions/src/tests/resources/keyPointMessages.csv
  functions/src/tests/resources/keyPointMessages.csv.license
  functions/src/tests/resources/mockChart.svg
  functions/src/tests/resources/mockHealthSummary.pdf
Labels: enhancement

#195 Check for all questionnaire response items (incl nested ones) to find correct link id
  functions/models/src/fhir/fhirQuestionnaireResponse.ts
Labels: bug

#201 Add custom providerName to health summary pdf
  README.md
  functions/models/src/types/userRegistration.ts
  functions/src/services/healthSummary/databaseHealthSummaryService.ts
Labels: enhancement

#200 Complete inactivity messages
  functions/src/services/trigger/triggerService.test.ts
  functions/src/services/trigger/triggerService.ts
Labels: bug

#203 Update SSO Information
  functions/data/organizations.json
Labels: enhancement

#205 Allow disabling of users
  README.md
  firestore.rules
  functions/models/src/functions/disableUser.ts
  functions/models/src/functions/enableUser.ts
  functions/models/src/index.ts
  functions/models/src/types/user.ts
  functions/models/src/types/userRegistration.ts
  functions/src/functions/deleteInvitation.test.ts
  functions/src/functions/disableUser.test.ts
  functions/src/functions/disableUser.ts
  functions/src/functions/enableUser.test.ts
  functions/src/functions/enableUser.ts
  functions/src/functions/enrollUser.test.ts
  functions/src/index.ts
  functions/src/services/credential/credential.ts
  functions/src/services/trigger/triggerService.ts
  functions/src/services/user/databaseUserService.test.ts
  functions/src/services/user/databaseUserService.ts
  functions/src/services/user/userService.mock.ts
  functions/src/services/user/userService.ts
  functions/src/tests/functions/testEnvironment.ts
  functions/src/tests/rules/users.test.ts
Labels: enhancement

#212 Fix linkspector issues
  README.md
Labels: documentation

#214 Do not require SSO ProviderId to match invitation
  functions/src/flags.ts
  functions/src/functions/blocking.ts
Labels: enhancement

#215 Fix FHIR Link cases
  README.md
Labels: documentation

#211 Use `npm-publish-package` action
  .github/workflows/production.yml
Labels: enhancement

#217 Update dependencies
  functions/models/package-lock.json
  functions/package-lock.json
Labels: dependencies

#218 Update video ids
  functions/data/videoSections.json
Labels: enhancement
